# Generated by Django 5.1.1 on 2024-09-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Conatct Us'},
        ),
    ]
